// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-wines.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { wines } from "npm:@/data/wines";
var list_wines_default = defineTool({
  name: "list_wines",
  title: "List wines",
  description: "List wines from the Weinfinder catalog with optional filters by color, style, price category, or food pairing.",
  inputSchema: {
    color: z.enum(["weiss", "rot", "rose"]).optional().describe("Filter by wine color."),
    style: z.string().optional().describe("Filter by taste style, e.g. leicht_frisch, fruchtig_aromatisch."),
    price_category: z.enum(["unter10", "10-20", "ueber20"]).optional().describe("Filter by price bracket."),
    food_pairing: z.string().optional().describe("Filter to wines matching this food pairing tag, e.g. fisch, pasta, kaese."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ color, style, price_category, food_pairing, limit }) => {
    const filtered = wines.filter(
      (w) => (!color || w.color === color) && (!style || w.style === style) && (!price_category || w.price_category === price_category) && (!food_pairing || w.food_pairing?.includes(food_pairing))
    );
    const results = filtered.slice(0, limit ?? 20).map((w) => ({
      id: w.id,
      name: w.name,
      weingut: w.weingut,
      price: w.price,
      color: w.color,
      style: w.style,
      grape_variety: w.grape_variety,
      region: w.region,
      food_pairing: w.food_pairing,
      link: w.link
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ total: filtered.length, results }, null, 2) }],
      structuredContent: { total: filtered.length, results }
    };
  }
});

// src/lib/mcp/tools/get-wine.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { wines as wines2 } from "npm:@/data/wines";
var get_wine_default = defineTool2({
  name: "get_wine",
  title: "Get wine details",
  description: "Return full details for a single wine by its ID.",
  inputSchema: {
    id: z2.string().min(1).describe("Wine ID, e.g. wein_001.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const wine = wines2.find((w) => w.id === id);
    if (!wine) {
      return {
        content: [{ type: "text", text: `No wine found with id ${id}.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(wine, null, 2) }],
      structuredContent: { wine }
    };
  }
});

// src/lib/mcp/tools/recommend-wine.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { matchWines } from "npm:@/lib/matchWines";
import { wines as wines3 } from "npm:@/data/wines";
var recommend_wine_default = defineTool3({
  name: "recommend_wine",
  title: "Recommend wine",
  description: "Run the Weinfinder matching algorithm and return the top wine plus alternatives for a set of quiz answers.",
  inputSchema: {
    occasion: z3.string().describe("Occasion, e.g. abend, essen, party, geschenk."),
    color: z3.string().describe("Preferred color: weiss, rot, rose, egal."),
    style: z3.string().describe("Taste style, e.g. leicht_frisch, fruchtig_aromatisch, kraeftig_intensiv."),
    food: z3.string().describe("Food pairing, e.g. fisch, fleisch, pasta, kaese, vegetarisch, keine."),
    price: z3.string().describe("Price bracket: unter10, 10-20, ueber20, egal."),
    acidity: z3.string().describe("Acidity preference: niedrig, mittel, hoch, egal.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const answers = input;
    const { top, alternative, alternative2, valueTip } = matchWines(wines3, answers);
    if (!top) {
      return {
        content: [{ type: "text", text: "No matching wine found for these preferences." }],
        isError: true
      };
    }
    const payload = { top, alternative, alternative2, valueTip };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "weinfinder-mcp",
  title: "Weinfinder MCP",
  version: "0.1.0",
  instructions: "Tools for the Weinfinder digital sommelier. Use `list_wines` to browse the catalog with filters, `get_wine` for the full detail of a specific wine, and `recommend_wine` to run the guided-quiz matching algorithm for a set of preferences.",
  tools: [list_wines_default, get_wine_default, recommend_wine_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
